### ISSUE TITLE
data.replace is not a function

### ISSUE THREAD

**Issue by renanborgez** [berzniz/now-logs#1]
[Ubuntu 15.04]
When i started the logging on terminal.

```

Connecting to https://logs.now.sh ...
Connected, showing logs for "test"
TypeError: data.replace is not a function
    at Socket.<anonymous> (/usr/lib/node_modules/now-logs/bin/logs.js:43:34)
    at Socket.Emitter.emit (/usr/lib/node_modules/now-logs/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/usr/lib/node_modules/now-logs/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/usr/lib/node_modules/now-logs/node_modules/socket.io-client/lib/socket.js:232:12)
    at Manager.<anonymous> (/usr/lib/node_modules/now-logs/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/usr/lib/node_modules/now-logs/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/usr/lib/node_modules/now-logs/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/usr/lib/node_modules/now-logs/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/usr/lib/node_modules/now-logs/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/usr/lib/node_modules/now-logs/node_modules/socket.io-parser/index.js:256:14)

```

**Comment by berzniz** [comment]
@renanborgez -- I added some guards, but I couldn't reproduce this.

Do you have an example of outputs of the program using the `now-logs` module that leads to a crash?
